### ISSUE TITLE
1.4.3 Rapid/Precise jogging presets don't work

### ISSUE THREAD

**Issue by cvandermey** [Sienci-Labs/gsender#478]
Normal preset in gsender works for jogging operations - z/x/y.  However, when selecting rapid/precise, the machine doesn't respond.  I see error 22 in the console: feeder $J=G20G91 Y0 F0
error:22 (Undefined feed rate)

**Comment by bigbearct** [comment]
Also doesn't seem to save them from job to job. Precise would go either really really precise and rapid would also go very slow until I would default the settings and then seemed to clear it up until I setup a new job and have to go thru it again.

**Comment by kglovern** [comment]
This should be resolved with next release.

**Comment by kglovern** [comment]
Let us know if 1.4.4 has resolved these issues for you.

**Comment by bigbearct** [comment]
1.4.4 still doesn't save or hold the settings. I usually have to do a restore settings for the 3 different speeds to work correctly.

**Comment by walidkayhan** [comment]
@bigbearct are you still facing this issue on the latest version, v1.4.6?

**Comment by bigbearct** [comment]
no issues since going 1.4.6

**Comment by walidkayhan** [comment]
That's great to hear 😃  if you notice another problem with jogging presets or anything else please open another issue
